### ISSUE TITLE
Spammed by an error

### ISSUE THREAD

**Issue by BrinDeNuage** [disturbedfood/TameProtect#1]
Hello, I installed your plugin on my server (Spigot 1.12) and when we interact with parrots the console is spammed by this error : 

[12:27:18] [Server thread/ERROR]: Could not pass event PlayerInteractEntityEvent to TameProtect v1.0.1
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-7228328-11323bf]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-7228328-11323bf]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:499) [spigot.jar:git-Spigot-7228328-11323bf]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [spigot.jar:git-Spigot-7228328-11323bf]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1568) [spigot.jar:git-Spigot-7228328-11323bf]
	at net.minecraft.server.v1_12_R1.PacketPlayInUseEntity.a(SourceFile:69) [spigot.jar:git-Spigot-7228328-11323bf]
	at net.minecraft.server.v1_12_R1.PacketPlayInUseEntity.a(SourceFile:13) [spigot.jar:git-Spigot-7228328-11323bf]
	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-7228328-11323bf]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_131]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_131]
	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot.jar:git-Spigot-7228328-11323bf]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:747) [spigot.jar:git-Spigot-7228328-11323bf]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:405) [spigot.jar:git-Spigot-7228328-11323bf]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot.jar:git-Spigot-7228328-11323bf]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot.jar:git-Spigot-7228328-11323bf]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
Caused by: java.lang.ClassCastException: org.bukkit.craftbukkit.v1_12_R1.CraftOfflinePlayer cannot be cast to org.bukkit.entity.Player
	at eu.crypticcraft.tameprotect.Protection.loadProtection(Protection.java:154) ~[?:?]
	at eu.crypticcraft.tameprotect.Handlers.CommandHandler.onEntityInteract(CommandHandler.java:83) ~[?:?]
	at eu.crypticcraft.tameprotect.EventListener.onEntityInteract(EventListener.java:152) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor397.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_131]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_131]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot.jar:git-Spigot-7228328-11323bf]
	... 15 more

**Comment by gjerm** [comment]
Hello, thank you for reporting this issue.

Unfortunately, I cannot reproduce this issue on my server. Could you download and see if this jar produces the same error? [Link](https://crypticcraft.eu/files/TameProtect.jar)

**Comment by BrinDeNuage** [comment]
Sorry I don't really know how the error appeared and I don't know what to do to make the error appear again :/

**Comment by gjerm** [comment]
From what I understand of the error, it appeared when trying to interact with an animal that isn't registered with TameProtect but has an owner. TameProtect will try to add it, but if the owner is offline it throws this error. The changes I made should prevent the error from being thrown.

**Comment by BrinDeNuage** [comment]
Ok thanks I'll tell you soon if it makes errors again, thanks for you help

**Comment by BrinDeNuage** [comment]
Also I wanted to know if it was possible to add a tp feature. Like /tp [animal name] to tp the animal to your position. It would be great because sometimes parrots are lost between two worls :/

**Comment by gjerm** [comment]
I may add a feature like that, it could quickly get complicated if a player owns many animals but it would be a useful feature.

For now, I have updated the plugin. If you do experience more errors, please do create an issue and I'll do my best to update it to fix these.
